// types for the JSON files generated by the etl process

interface ReverseMap {
  [key: string]: {
    utf_code: string;
    ids_strings: {
      ids: string;
      locales: string;
    }[];
  };
}

interface ForwardMap {
  [key: string]: string[];
}

type BaseRadicals = string[];
interface StrokeCount {
  [key: string]: number;
}

interface VariantRadicals {
  [key: string]: Set<string>;
}

interface Readings {
  [key: string]: {
    [key: string]: string;
  };
}

interface QueryResults {
  charToSet: {
    [key: string]: Set<string>;
  } | null;
  res: Set<string> | null;
}
